<?php
$root = dirname(__DIR__).DIRECTORY_SEPARATOR;
define('APP_PATH', $root.'App'.DIRECTORY_SEPARATOR);
define('BROKERS_PATH', APP_PATH."Brokers".DIRECTORY_SEPARATOR);
define('MODELS_PATH', APP_PATH."Models".DIRECTORY_SEPARATOR);
define('PUBLIC_PATH', $root.'Public'.DIRECTORY_SEPARATOR);
define('VIEWS_PATH', PUBLIC_PATH.'Views'.DIRECTORY_SEPARATOR);